spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  # Maria DB ??
  datasource:
    hikari:
      maximum-pool-size: 4
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://211.180.247.168:3306/amon
    username: amon
    password: dpdlahs1!
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
#    host: 192.168.0.52
#    port: 587
    username: admin@amonsoft.co.kr
    password: aiaz rrwd fsww jrgl
#    username: anrh0213@amonsoft.co.kr
#    password: dpdlahs1!A
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mappers/**/*.xml

logging:
  level:
    org.apache.ibatis: DEBUG
    org.mybatis: DEBUG
  config: classpath:config/log4j2-local.yml








